spring:
    application:
        name: demos
        appName: demo_web
    rabbitmq:
        host: rabbit
        port: 5672
        username: root
        password: root
    mail:
        host: smtp.exmail.qq.com
        username: xujiancheng@touker.com
        password: 腾讯企业邮箱密码
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: false
                        required: false
management:
    security:
        enabled: false
    info:
        git:
            mode: full
info:
    app:
        name: demos
        appName: demo_web中文